### ISSUE TITLE
add language Viet nam 

### ISSUE THREAD

**Issue by hoanmaster321** [dayanch96/ShowMyTouches#6]
"Enable" = "Bật";

"OnlyRecording" = "Hiển thị chế độ ghi màn hình";
"OnlyRecordingDesc" = "Hiển thị báo cảm ứng trong quá trình ghi màn hình";

"TouchColor" = "Màu cảm ứng";
"BorderColor" = "Màu viền";

"AnimationDuration" = "Thời gian hoạt ảnh";
"TouchSize" = "Kích thước cảm ứng";
"CornerRadius" = "Bán kính góc";
"BorderWidth" = "Độ rộng viền";

"ResetSettings" = "Khôi phục cài đặt về mặc định";

"FollowMe" = "Theo dõi tôi trên Twitter";
"SourceCode" = "Mã nguồn";

"TipJar" = "Tiền Boa";
"Donate.PayPal" = "Ủng hộ tôi qua PayPal <3";

"Support" = "Hỗ trợ tôi";
"Donate.KoFi" = "Mua cho tôi một tách cà phê <3";

**Comment by dayanch96** [comment]
I've had translation sent from twitter, please take a look at it and let me know if it is correct translation, thanks

**Comment by hoanmaster321** [comment]
It is google tranlate. Not perfect

**Comment by dayanch96** [comment]
Thanks for clarifying. I'll add your translation when i’ll on my device
